<<<<<<< HEAD
# Generated by Django 2.2.5 on 2021-04-04 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 2.2.5 on 2021-04-03 17:47

from django.db import migrations, models
>>>>>>> fa6c254c8ad9c40b6332389b78c08fb063522724
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> fa6c254c8ad9c40b6332389b78c08fb063522724
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
=======
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
>>>>>>> fa6c254c8ad9c40b6332389b78c08fb063522724
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=80)),
<<<<<<< HEAD
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=140)),
                ('guests', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('instant_book', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> fa6c254c8ad9c40b6332389b78c08fb063522724
            ],
            options={
                'abstract': False,
            },
        ),
    ]
