# Generated by Django 2.2.12 on 2021-04-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210405_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_type',
            new_name='room_type_a',
        ),
    ]
